### ISSUE TITLE
Shell error when running latest docker image

### ISSUE THREAD

**Issue by theetrain** [mermaid-js/mermaid-cli#100]
Thank you for maintaining mermaidJS.

**Describe the bug**

When running the latest docker image `minlag/mermaid-cli:latest` (presumably v8.9.1-beta.2), the following error appears when I run `mmdc`:

```sh
sh: 1: sh: mmdc: not found
```

**To Reproduce**

Run the following command:

```sh
docker run --rm --entrypoint mmdc minlag/mermaid-cli:latest
```

Observed response:

```sh
docker: Error response from daemon: OCI runtime create failed: 
container_linux.go:370: starting container process caused: 
exec: "mmdc": executable file not found in $PATH: unknown.
```

**Expected behavior**

Expected response:

```sh
Please specify input file: -i <input>
```

**Workaround**

Run version v8.9.0:

```sh
docker run --rm --entrypoint mmdc minlag/mermaid-cli:8.9.0 

# output
Please specify input file: -i <input>
```

If `latest` is pointing to a beta, perhaps it should only point to the latest stable version of Mermaid.

**Desktop:**

- OS: MacOS 10.15.7
- Docker: 3.1.0; engine 20.10.2

**Comment by MindaugasLaganeckas** [comment]
@theetrain : very nice catch. Would you have the time to work on the PR? This is the code line you are looking for :) https://github.com/mermaid-js/mermaid-cli/blob/eb423cf68f7a0f0ead5bdd69b22d161f34f89602/.github/workflows/release-publish.yml#L72

**Comment by MindaugasLaganeckas** [comment]
@theetrain : the docker image will get the latest tag assigned only when built from master from release tag. https://github.com/mermaid-js/mermaid-cli/blob/3de00c75cc2ce779cfd69e57c45729e5d72231a1/.github/workflows/compile-mermaid.yml#L74
