### ISSUE TITLE
Mermaid 8.0.0-rc.8 creates SVG files that do not display correctly in Inkscape and Latex

### ISSUE THREAD

**Issue by RedX2501** [mermaid-js/mermaid-cli#103]
We user mermaid.cli from mermaid-filter to generate PDF files from Markdown.

When using mermaild-cli 0.4.6 it was creating black tags for the labels. Firefox version 0.5.6 did display the SVG correctly though.

![bad svg](http://pichost.org/images/2018/05/23/2018-05-23_15h44_04.png)

According to devDependencies mermaid.cli uses mermaid 8.0.0-rc.8.
Replacing the minified mermaid version with 7.1.2 fixed the problem. Mermaid 8.0.0-rc.8 still had the issue.

**Comment by jgreywolf** [comment]
Moving to CLI after conversation with @knsv

**Comment by LuisBL** [comment]
does not display correctly on LibreOffice too

**Comment by MindaugasLaganeckas** [comment]
I am closing the issue, because it seems related to another project and not mermaid-cli. If you disagree, please, reopen the issue and give a short status update. Thanks! 😄 🏅

**Comment by Grummfy** [comment]
well most of the tools don't render it properly, so I'm not sure it's entirely to the tools
I Have the same issue with
* intelij (phpstorm)
* imagemagick (with convert command)
* libreoffice
* firefox
* inkscape
* ...

Globally any tools that I use have some sort of issue, and they use different technology (c, rust, java, node, etc) so it's seems more global.

**Comment by chuxubank** [comment]
Emacs (with librsvg support) do not display it correctly too.
![image](https://user-images.githubusercontent.com/17001575/150905080-08b4ad07-ce9a-472c-84e1-f367ee236402.png)
