### ISSUE TITLE
live editor code, preview and configuration windows should be resizable

### ISSUE THREAD

**Issue by suhashpatil** [mermaid-js/mermaid-cli#106]
**Is your feature request related to a problem? Please describe.**
When my mermaid code is long, the small window is a hindrance.

**Describe the solution you'd like**
 All sub-windows hence, should be made resizable.

**Describe alternatives you've considered**
Using other implementations which are worse choices to make!

**Comment by MindaugasLaganeckas** [comment]
@suhashpatil : this repository is for mermaid-cli tool. Please, move your issue to https://github.com/mermaid-js/mermaid-live-editor

**Comment by suhashpatil** [comment]
moving to live editor
