### ISSUE TITLE
Maximum text size in diagram exceeded

### ISSUE THREAD

**Issue by yellowred** [mermaid-js/mermaid-cli#113]
**Describe the bug**
When I try to generate a diagram for mermaid file of size 757KB what I get is an empty svg/png with text: `Maximum text size in diagram exceeded`

**To Reproduce**
Generate `input.mmd` size greater than 700KB.
Run: `docker run -it -v /Users/olegkubrakov/Sites/bulldog/scripts/tx_flowchart:/data minlag/mermaid-cli -i /data/input.mmd -o output.png`

**Expected behavior**
A graphic representation of a diagram expected.

**Screenshots**
![Screenshot 2021-03-29 at 9 58 51 AM](https://user-images.githubusercontent.com/3875329/112777679-63827700-9075-11eb-91b4-04e12bb1ef1f.png)

**Comment by SebastianC** [comment]
Have you tried overriding the maxTextSize value in the config?

cli:
```
-i /data/input.mmd -o output.png --configFile="mermaidRenderConfig.json"
```

mermaidRenderConfig.json looks like:
```json
{
    "maxTextSize" : 99999999
}
```

From source line:
https://github.com/mermaid-js/mermaid/blob/c269dc822c528e1afbde34e18a1cad03d972d4fe/src/defaultConfig.js#L55

**Comment by MindaugasLaganeckas** [comment]
@yellowred : I will close this issue as the fix is described by @SebastianC . You are welcome to reopen the issue, if the fix does not work.

**Comment by mhosman** [comment]
The mermaid.initialize ignores the value.
