### ISSUE TITLE
Feature: allow `mmdc` to parse Markdown files

### ISSUE THREAD

**Issue by AlexanderWillner** [mermaid-js/mermaid-cli#130]
**Is your feature request related to a problem? Please describe.**
I'm always frustrated when editing a Mermaid diagram in VSCode in a Markdown file and I can't export it easily via CLI using `mmdc`.

**Describe the solution you'd like**
I'd like `mmdc -i diagram.md` to produce `diagram.md.svg`.

**Describe alternatives you've considered**
One can copy and paste the diagram to a new file without the back ticks, but this is unpleasant.

**Additional context**
In case more than one diagram is found in the file, multiple files could be generated.

**Comment by MindaugasLaganeckas** [comment]
@knsv: do you agree with the feature described above? I see it as a great help to our users, but conceptually md files are not mmd files.

**Comment by knsv** [comment]
This makes total sense. There are some things to consider though.

I assume that the markdown file would use markdown formatting and that the diagram would come in a code chunk like this one:
<pre>
```mermaid
flowchart
   A-->B
```
</pre>
What do we do if, or rather when, there are multiple diagrams in the markdown file?

My take would be to:
* When the input file is a mmd file, it should work as today
* When the input file is a md file, the new functionality should kick in
* Only mermaid code blocks are handled
* When there are multiple code blocks the results will be extracted using a count creating `diagram.md-1.svg` ... `diagram.md-1.svg`

I think this would be a very strong feature. It would increase the various situations where the cli tool could be used significantly.
