### ISSUE TITLE
PNGs rendered with docker image are missing emojis

### ISSUE THREAD

**Issue by elf-pavlik** [mermaid-js/mermaid-cli#131]
**Describe the bug**
Rendering to PNG with docker-image is missing emojis

**To Reproduce**

1. fork (or just see) https://github.com/elf-pavlik/data-interoperability-panel
2. see results of github action https://github.com/elf-pavlik/data-interoperability-panel/blob/gh-pages/primer/diagrams/home.alice.example.flow.mmd.png
3. see flowchart source: https://github.com/elf-pavlik/data-interoperability-panel/blob/gh-pages/primer/diagrams/home.alice.example.flow.mmd
4. verify gitub action: https://github.com/elf-pavlik/data-interoperability-panel/blob/main/.github/workflows/publish-proposals.yml#L39

**Expected behavior**
Rendered PNG should include emojis from the source

**Screenshots**

rendered as PNG using docker-container in github action

![image](https://user-images.githubusercontent.com/876431/122427137-79a62200-cf56-11eb-8d9c-3042ab7255bf.png)

rendered as PNG locally using npm module

![image](https://user-images.githubusercontent.com/876431/122427330-a4907600-cf56-11eb-8894-16e602fdcd33.png)

**Comment by MindaugasLaganeckas** [comment]
Thank you so much for the bug report. This issue might be related to #93

**Comment by elf-pavlik** [comment]
Yes, actually my issue might be a duplicate. I subscribed to the other one so please feel free to close this one.
BTW Please notice on my screenshots that PNG from docker-image is using very different font. Second PNG which I would consider using correct font and rendering emojis was made on MacOS 10.15.7

I found this PR which adds font with emoji to docker image, maybe it wold be relevant here https://github.com/garris/BackstopJS/pull/1010/files

Another possibly relevant link https://wiki.alpinelinux.org/wiki/Emojis

**Comment by MindaugasLaganeckas** [comment]
@elf-pavlik : would you like to work on a PR? 😄

**Comment by elf-pavlik** [comment]
sure #132
