### ISSUE TITLE
Feature Request: Ability to raise an error when the provided input is invalid

### ISSUE THREAD

**Issue by axelson** [mermaid-js/mermaid-cli#138]
**Is your feature request related to a problem? Please describe.**
I'm creating a CI pipeline that processes mermaid diagrams

**Describe the solution you'd like**
I'd the CI pipeline to unambiguously detect when a mermaid diagram has a syntax issue

**Describe alternatives you've considered**
Running OCR on the image looking for the string "syntax error in graph"

**Additional context**
Ideally it would returned via exit status and a warning printed to STDERR.

**Comment by katrinleinweber** [comment]
A non-0 exit code would also be useful for `mmdc` commands used within Git hooks.
