### ISSUE TITLE
Running the CLI command without passing any arguments throws an error, when it should probably display the "help" text instead

### ISSUE THREAD

**Issue by Duckwhale** [mermaid-js/mermaid-cli#139]
**Describe the bug**
Running the CLI command without passing any arguments throws an error.

**To Reproduce**

1. Install Mermaid-CLI via `npm install -g @mermaid-js/mermaid-cli` (to test it out since I've never used it before)
2. Type ``mmdc`` (I assume this means "Mermaid CLI"? I'd expect ``mermaid``, which is far more intuitive, but oh well)
3. An error is printed and as a new user, I'm flabbergasted for a second as I have to guess that it means "I have no file to open"

**Expected behavior**
I'd expect to see the output of ``mmdc -h``, which is standard behaviour for CLI tools?

**Screenshots**
![image](https://user-images.githubusercontent.com/16489133/125178893-30f62780-e1e9-11eb-96d7-422e0c05f51a.png)

---

I'd expect this to be the first thing any user does (you didn't think people read all the documentation first, did you? :joy: ) and being greeted with an error isn't what most people will be expecting, even if it makes sense (in retrospect) that you'd require some files to be passed as input.

Luckily, it's very easy to fix. I think even just showing the help command's output by default is sufficient for a CLI tool, though it could likely be improved further, e.g. by linking to proper documentation or being easier to parse at a glance (visual improvement).

**Comment by MindaugasLaganeckas** [comment]
@Duckwhale : I could not reproduce your issue exactly. Not sure, which version of the mermaid-cli you have installed, but added a help text if no input argument is provided. PR: #173
The feature will be available with the next release.
