### ISSUE TITLE
Provide better error message for .md files not containing valid Markdown

### ISSUE THREAD

**Issue by ghtyrant** [mermaid-js/mermaid-cli#160]
**Is your feature request related to a problem? Please describe.**
I just tried mmdc for the first time, copy-pasted a sequence diagram example from the mermaid documentation and out of habit named my input file `test.md`.
Running mmdc as follows:
`mmdc -i test.md -o test.svg -t dark -b transparent`
yields the following output
```
/usr/lib/node_modules/@mermaid-js/mermaid-cli/index.bundle.js:210
    if (matches.length > 0) {
                ^

TypeError: Cannot read properties of null (reading 'length')
    at /usr/lib/node_modules/@mermaid-js/mermaid-cli/index.bundle.js:210:17
    at Generator.next (<anonymous>)
    at step (/usr/lib/node_modules/@mermaid-js/mermaid-cli/index.bundle.js:4:191)
    at /usr/lib/node_modules/@mermaid-js/mermaid-cli/index.bundle.js:4:361
```

**Describe the solution you'd like**
A more descriptive error message, e.g. "Input file expected to contain valid Markdown. Don't use the file extension .md if you just want to render a mermaid diagram." or probably something less clunky would be helpful.

**Comment by MindaugasLaganeckas** [comment]
@ghtyrant : Thanks for reporting the issue! Would you like to work on the solution? I would be glad to review your PR 😄

**Comment by ghtyrant** [comment]
@MindaugasLaganeckas Done :slightly_smiling_face:
