### ISSUE TITLE
Implement an automated test for #165

### ISSUE THREAD

**Issue by MindaugasLaganeckas** [mermaid-js/mermaid-cli#166]
An automated test for #165 is needed.

**Comment by MindaugasLaganeckas** [comment]
@ghtyrant : would you be interested in implementing an automated test for #165. For example, 
1. you can show that mermaid-cli does not crash when called with the input file in the PR
2. you can call mermaid-cli with the input file from the PR and save the log output to the file. Afterwards, you can assert, that the output does not change.
Since it is a small CLI tool, we focus on e2e test here more than on unit tests.
A good place to put the new tests: https://github.com/mermaid-js/mermaid-cli/blob/master/run-tests.sh
BTW, Hactoberfest is coming! 👍

**Comment by ghtyrant** [comment]
Not sure about my implementation, can you have a look at #170 ?
