### ISSUE TITLE
failed to render svg image of state diagram when there are some strings with '\n'  

### ISSUE THREAD

**Issue by ruoting0103** [mermaid-js/mermaid-cli#169]
**Describe the bug**
failed to render svg image of state diagram when there are some strings with '\n'  

**To Reproduce**
a.mmd:
```
stateDiagram-v2
    a --> b : link \n note
```
`mmdc -i a.mmd -o a.svg`

the generated 'svg' image is invalid.

**Expected behavior**
render svg image successful 

**Env**
- OS: mac os 
- Version : 8.11.0

**Comment by MindaugasLaganeckas** [comment]
Thanks for reporting the issue! We had a similar one already, but it seems we have some quality problems in our processes.

**Comment by ruoting0103** [comment]
</br> no works also for svg image :(

btw , 'png' image works well for both '\n' and '</br>'

**Comment by ruoting0103** [comment]
> Can you change `\n` to `</br>` instead?

no works also for svg image :(

btw , 'png' image works well for both '\n' and `</br>`

**Comment by MindaugasLaganeckas** [comment]
I am sorry, I meant `<br/>`. Please, try that.

**Comment by MindaugasLaganeckas** [comment]
I will close this issue with the resolution to change from `\n` to `<br/>`. mermaid-cli cannot accommodate all possible special symbols. Some preprocessing of the diagram file may be needed before calling mermaid-cli.
