### ISSUE TITLE
Markdown Graph Detection Broken for CRLF Files

### ISSUE THREAD

**Issue by dominicdoty** [mermaid-js/mermaid-cli#183]
Detection of mermaid graphs embedded in markdown does not work for CRLF (\r\n) files.

Saving the file as LF only works as a temporary workaround.

It looks like line 206 in  src/index.js is the culprit.

Proposed solutions
 * Strip all \r from the string `str.replace('\r', '')`
 * Modify regex to catch optional carriage return `const matches = definition.match(/^```(?:mermaid)(\r?\n([\s\S]*?))```$/gm);`

**Comment by MindaugasLaganeckas** [comment]
Can you provide screenshots/error messages etc showing the error? From the description, it is not clear what does not work. BTW, can you attach the input file you use to the issue?

**Comment by dominicdoty** [comment]
Gitlab won't let me attach my markdown file for replication, but the contents are below. Note that this **must** be saved with CR/LF line endings for this error to appear.

~~~
# My Fake Markdown

```mermaid
flowchart TB
    test->chart
    chart->test
```
~~~

I'm running this via docker in windows:
```
docker run -it -v D:/test_mermaid_md:/data minlag/mermaid-cli  -i /data/replicate.md
```

Output from the program is 
```
No mermaid charts found in Markdown input
```

Re-save the file as LF only line endings, and the same file produces 
```
Found 1 mermaid charts in Markdown input
 - /data/replicate-1.md.svg
```


When using Windows style CRLF endings, the regex (`match(/^```(?:mermaid)(\n([\s\S]*?))```$/gm);`) will not match because it is looking for an explicit `\n`, when in a Windows style CRLF file, the contents will be `mermaid\r\n`

**Comment by MindaugasLaganeckas** [comment]
OK. Thanks a lot for the input. I think the error can be fixed, but cannot give you an ETA 😉

**Comment by dominicdoty** [comment]
Never written any JS before but I'll see if I can take a crack at it this weekend 😃 
Would you need a test case for it as well?

**Comment by MindaugasLaganeckas** [comment]
Fantastic! Yes, I would like a test.
Put the test data in here https://github.com/mermaid-js/mermaid-cli/tree/master/test-positive. You do not need to do anything else regarding the test!
Review manually that the fix removes the problem.
The automatic test will generate a new png file which will be kept as a reference file for the future regressions.
When you submit your PR, I will review it and accept. 😄

**Comment by Wen-Tao-Zhang** [comment]
Thanks to the OP for pointing that out. I got stuck today just because of that.

FWIW, I also found that there should not be whitespaces right after `` ```mermaid``.
