### ISSUE TITLE
Top and bottom white margin  issue in a generated png

### ISSUE THREAD

**Issue by cptaimless** [mermaid-js/mermaid-cli#202]
Hi,

Context : When I generate a docx file (pandoc + mermaid-filter), I have top and bottom white margin for one  mermaid graph type :  sequenceDiagram...

Example :
![image](https://user-images.githubusercontent.com/28149265/145268349-0d84f33e-3b62-4959-a5f2-dee334c34048.png)

Does anyone have an idea of the problem ? 

I tested directly mmdc in command line which reacts differently in the 2 contexts: 
- through pandoc + mermaid-filter
- in a terminal

I lean towards environment variables issue... Hence my post for an expert on the subject for a little bit help !

Thanks in advance

I'm working un Bulleyes Debian / node 16  / pandoc 2.16.2.1

**Comment by MindaugasLaganeckas** [comment]
Hi @cptaimless try asking the same question in mermaid slack channel 😄

**Comment by robross0606** [comment]
I'm seeing the same issue.  Absolutely massive amounts of whitespace at top and bottom of image.  2-3 times the size of the image itself in each margin. 😞

**Comment by robross0606** [comment]
FWIW, I was able to resolve the issue by adding this to the top of my mmd file:
```
%%{init: {"flowchart":{"useMaxWidth": false}}}%%
```

**Comment by MindaugasLaganeckas** [comment]
Would you share your workaround in the mermaid project?

**Comment by robross0606** [comment]
That’s where I found the workaround

**Comment by MindaugasLaganeckas** [comment]
Closing this issue, since it is a bug in the mermaid project.
