### ISSUE TITLE
Cardinality / Multiplicity are not shown 

### ISSUE THREAD

**Issue by hornse** [mermaid-js/mermaid-cli#208]
Hi there,

I just recognized, that there a no Cardinality / Multiplicity in a class diagramm. 
Perhaps I made something wrong, but I also couldn't find the Cardinality / Multiplicity in the example class diagramm on the website: https://mermaid-js.github.io/mermaid/#/classDiagram you

With kong regards 
Seb

**Comment by MindaugasLaganeckas** [comment]
Hi @hornse : this question belongs to the mermaid project. mermaid-cli is only a thin client over mermaid library. Features, such as you mention here, are implemented in the mermaid library. Feel free to reopen if you disagree 😉

**Comment by hornse** [comment]
Oh sorry and thanks for answering :-)
