### ISSUE TITLE
mermaid-cli 8.14.0 breaks puppeteer?

### ISSUE THREAD

**Issue by ewe2** [mermaid-js/mermaid-cli#246]
**Describe the bug**
I install mermaid-cli with npm according to the instructions, and get the following error:

```
ewe2@marvin:~$ ./node_modules/.bin/mmdc -h
/home/ewe2/node_modules/puppeteer/lib/cjs/puppeteer/common/AriaQueryHandler.js:30
const attributeRegexp = /\[\s*(?<attribute>\w+)\s*=\s*(?<quote>"|')(?<value>\\.|.*?(?=\k<quote>))\k<quote>\s*\]/g;
                        ^

SyntaxError: Invalid regular expression: /\[\s*(?<attribute>\w+)\s*=\s*(?<quote>"|')(?<value>\\.|.*?(?=\k<quote>))\k<quote>\s*\]/: Invalid group
    at Object.<anonymous> (/home/ewe2/node_modules/puppeteer/lib/cjs/puppeteer/common/AriaQueryHandler.js:30:25)
    at Module._compile (module.js:643:30)
    at Object.Module._extensions..js (module.js:654:10)
    at Module.load (module.js:556:32)
    at tryModuleLoad (module.js:499:12)
    at Function.Module._load (module.js:491:3)
    at Module.require (module.js:587:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (/home/ewe2/node_modules/puppeteer/lib/cjs/puppeteer/common/QueryHandler.js:19:31)
    at Module._compile (module.js:643:30)

```

**Steps to reproduce the behavior:**

1. npm install @mermaid-js/mermaid-cli
2. ./node_modules/.bin/mmdc -h

**Expected behaviour:**
Help options of the program, at the very least. This makes the program unusable.

**Desktop (please complete the following information):**

- OS: Linux Debian Bookworm amd64
- Browser chrome/firefox
- Version whatever the latest is.

**Additional context**
I'm aware there are a plethora of modules in a node directory tree, but obviously puppeteer is one of the key dependencies of mermaid-cli. I searched the issues both open and closed and didn't see anything directly touching this issue, I was hoping it might have been an older versions bug.  puppeteer is at version 13.0.0.

**Comment by MindaugasLaganeckas** [comment]
I could not reproduce the problem locally.
BTW, we have many regression tests, that are run against every change we made.
I would say the problem is in local setup.
If possible, try to use the docker version of mermaid-cli.
Hope that helps.

**Comment by ewe2** [comment]
I fixed it, it was indeed an issue with node/npm, I tried to install mermaid-cli using yarn but it wasn't working because node wasn't up to date for chalk, so that clued me into the real issue, used nvm to update node/npm properly and then used yard to install mermaid-cli and it works now.  It seems to be a fragile system, no wonder you have to regression test! Thanks.
