### ISSUE TITLE
Calling mermaid-cli directly via a node API (without child processes)

### ISSUE THREAD

**Issue by thomkeh** [mermaid-js/mermaid-cli#247]
**Is your feature request related to a problem? Please describe.**
I want to create a plugin for [markdown-it](https://github.com/markdown-it/markdown-it) for server-side rendering of mermaid diagrams.

**Describe the solution you'd like**
I can call mermaid-cli in a child process but it would be much nicer if I could call it directly via a node API.

**Describe alternatives you've considered**
There is a [plugin for remark](https://github.com/temando/remark-mermaid) which does call mermaid-cli via a child process, but this makes the code quite complicated. (Also, the plugin is very out-of-date.)

**Additional context**
As I understand it, mermaid can only render a diagram when running in a browser. That's why mermaid-cli needs to use `puppeteer`. So, I cannot call mermaid directly in my server-side markdown plugin. I would basically have to re-create mermaid-cli except for the CLI interface. So, do you think it's possible to provide an API for mermaid-cli that can be called directly from node processes?

**Comment by MindaugasLaganeckas** [comment]
My immediate input is that mermaid cli is already a very thin client over the mermaid library. If you look at the code, there is only a few lines of extra code.
I am not totally sure about your requirements, but try to look into the mermaid live editor project https://github.com/mermaid-js/mermaid-live-editor
Finally, if you still think that calling mermaid-cli from the API is exactly what you need, try to copy the needed code parts from the index.js file to your plugin and send a link to your project (the copied lines). Then I can have a look what exactly is needed from the mermaid-cli. Does that sound like a plan?

**Comment by thomkeh** [comment]
> try to copy the needed code parts from the index.js file to your plugin and send a link to your project (the copied lines)

Yes, that sounds very reasonable.

**Comment by thomkeh** [comment]
Turns out someone has already done this: https://github.com/muhammadmuzzammil1998/headless-mermaid . That package has fewer config options, but it's enough for me.

I see now that it's probably not worth it to add the functionality to `mermaid-cli`, so I'm going to close this.
