### ISSUE TITLE
Output path can't has period '.' symbol, or will encounter ENOENT: no such file or directory

### ISSUE THREAD

**Issue by SplitGemini** [mermaid-js/mermaid-cli#258]
**Describe the bug**
Output path can't has period '.' symbol, or will encounter ENOENT: no such file or directory

**To Reproduce**

1. npx mmdc -i test.md -o /path/to/has.period/test.png
2. [Error: ENOENT: no such file or directory, open '/path/to/has-1.period/test.png']

**Expected behavior**
Resolve period properly

**Screenshots**

**Desktop (please complete the following information):**

- OS: Linux Ubuntu 20.04
- Browser 
- Version 8.14.0

**Additional context**

**Comment by SplitGemini** [comment]
code at [here](https://github.com/mermaid-js/mermaid-cli/blob/e3e59cc81c4ff33bd295fb27f36e1f9e771fca2d/src/index.js#L231)

```javascript
 // Output can be either a template image file, or a `.md` output file.
 //   If it is a template image file, use that to created numbered diagrams
 //     I.e. if "out.png", use "out-1.png", "out-2.png", etc
 //   If it is an output `.md` file, use that to base .svg numbered diagrams on
 //     I.e. if "out.md". use "out-1.svg", "out-2.svg", etc
 const outputFile = output.replace(/(\..*)$/,`-${diagrams.length + 1}$1`).replace(/(\.md)$/, '.svg');
 const outputFileRelative = `./${path.relative(path.dirname(path.resolve(output)), path.resolve(outputFile))}`;

```
For example, a path `./conf.d/test.png` will be replace to `./conf-1.d/test.png`

**Comment by ShaneMurphy2** [comment]
Yeah this is pretty annoying if you use absolute paths and your username has a '.' in it like mine does.
