### ISSUE TITLE
Cannot export erDiagram (database diagram)

### ISSUE THREAD

**Issue by ShinJustinHolly3317** [mermaid-js/mermaid-cli#268]
**Describe the bug**
I cannot export database ER diagram as  png, while I can  export sequence flow or other diagram normally.

**To Reproduce**
Below is an ER diagram example from official website.

```
erDiagram
    CUSTOMER ||--o{ ORDER : places
    ORDER ||--|{ LINE-ITEM : contains
    CUSTOMER }|..|{ DELIVERY-ADDRESS : uses
```

I executed below command
`mmdc -i ./inuptDB.mmd -o ./outputDB.png -t neutral -H 800 -w 2400`

then got this error

```
Expecting 'DIR', 'TAGEND', 'TAGSTART', 'UP', 'DOWN', got 'ALPHA'
    at Yt.parseError (file:///Users/justinkao/.nvm/versions/node/v12.22.10/lib/node_modules/mermaid.cli/mermaid.min.js:1:486512)
    at Yt.parse (file:///Users/justinkao/.nvm/versions/node/v12.22.10/lib/node_modules/mermaid.cli/mermaid.min.js:1:487678)
    at Object.e.getClasses 
```

**Expected behavior**
Should get a png image.

**Comment by NoriyukiMatsumoto** [comment]
@ShinJustinHolly3317 
This problem was resolved in ver 9.1.2.
