### ISSUE TITLE
Possibility to provide binaries with latest releases and not only source code

### ISSUE THREAD

**Issue by kirk86** [mermaid-js/mermaid-cli#275]
Hi, is it possible to provide binaries and not just source code?

I think that should be doable through github actions and continuous integration, deploying different VMs for each operating system and compile the equivalent binaries.

**Comment by MindaugasLaganeckas** [comment]
We release the binaries to npmjs.org
Why is it not enough?

**Comment by kirk86** [comment]
If I understand correctly one needs the nodejs or specifically the node package manager in order to install `mermaid-cli` correct?

> Why is it not enough?

Scenario, user on a server without admin access, no nodejs no npm, no nothing of that sort. 
How do you install `mermaid-cli` in this case?

Or, if possible release `mermaid-cli` as conda package as well?

**Comment by MindaugasLaganeckas** [comment]
Well, maybe there is something I do not understand, but nodejs is an interpreted language and I am not aware of OS dependent binary executable. Today we do not build such anyways. 
Have a look here https://stackoverflow.com/questions/70351244/how-to-compile-whole-typescript-project-to-executable
I do not think there is a good solution to your problem.

**Comment by MindaugasLaganeckas** [comment]
Closing this issue. You are welcome to reopen if you disagree.
