### ISSUE TITLE
Mermaid syntax errors are not displayed

### ISSUE THREAD

**Issue by fconil** [mermaid-js/mermaid-cli#276]
**Describe the bug**
When the input file contains a syntax error, the output is "Generating single mermaid chart" and the generated image contains "Syntax error in graph".

**To Reproduce**

I am using the docker container

1. My input file is in `$HOME/Mermaid` folder
2. Execute  : `docker run -u 1000 -it --rm -v $HOME/Mermaid:/data minlag/mermaid-cli -i "/data/seq-diagram.mmd" -o "/data/seq-diagram.png"`
3. You get the "Generating single mermaid chart" message and the generated image contains "Syntax error in graph"

Inside the container I do not get any other message 

1. My input file is in `$HOME/Mermaid` folder
2. Go inside the container : `docker run -u 1000 -it --rm --entrypoint /bin/sh -v $HOME/Progs/Mermaid:/data minlag/mermaid-cli`
3. Execute : `./node_modules/.bin/mmdc -p "/puppeteer-config.json" -i "/data/seq-diagram.mmd" -o "/data/seq-diagram.png"`
4. You get the "Generating single mermaid chart" message and the generated image contains "Syntax error in graph"

**Expected behavior**
I would like to see the syntax error so that I can fix it

```
Parse error on line 30:
...ger->>ABC auth->> User    SMS au
-----------------------^
Expecting 'TXT', got 'SOLID_ARROW'
```

**Screenshots**
![seq-diagram](https://user-images.githubusercontent.com/809748/161984741-645c8808-971f-40a4-9c4b-1185f3fed781.png)

**Desktop:**

- OS: Ubuntu 
- Version 20.04
- Browser inside the container : 
```
$ /usr/bin/chromium-browser --version
Chromium 99.0.4844.84

$ ./node_modules/.bin/mmdc -p "/puppeteer-config.json" --version
8.14.0
```

**Additional context**
I am not used to JavaScript but it seems like the following question in SO : https://stackoverflow.com/questions/51907677/log-console-calls-made-in-client-side-code-from-the-puppeteer-node-js-process

It seems that you could catch console events that happen in puppeteer / chromium to log them in Node ... as I understand it

**Comment by MindaugasLaganeckas** [comment]
We are aware of the issue and I have created a PR a long time ago in the mermaid project to fix the issue https://github.com/mermaid-js/mermaid/pull/2379 
You are welcome to support my PR by giving 👍

**Comment by multimeric** [comment]
It looks like your patch is now released upstream: https://github.com/mermaid-js/mermaid/commit/473aced449406aa8dd0289b030fd38c1550e88e8. Does anything need to be done to log the errors to the console when using `mermaid-cli`?

**Comment by MindaugasLaganeckas** [comment]
@multimeric : maybe you can help me a bit. I do not see that this change has been actually released. There is no mention in the mermaid release notes and if I call the new function, I get an error: https://github.com/mermaid-js/mermaid-cli/runs/6467149774?check_suite_focus=true
Unfortunately, I do not have the time now to investigate further.

**Comment by multimeric** [comment]
Oh right, so your new function isn't being exported unfortunately: 
https://github.com/mermaid-js/mermaid/blob/24eb2123e4670bff6bbde9746b17b005e94ccf34/src/mermaid.js#L209-L225

You may need to add a PR to add it to the exported object.

**Comment by MindaugasLaganeckas** [comment]
Thank you! 😄

**Comment by MindaugasLaganeckas** [comment]
@multimeric Done! https://github.com/mermaid-js/mermaid/pull/3052 Thank you for your help! You are welcome to create PRs for the functionality which is missing in mermaid-cli - I will review them and accept if no issues 😄
