### ISSUE TITLE
update brew formula to work with 9.0.3

### ISSUE THREAD

**Issue by yogurtearl** [mermaid-js/mermaid-cli#288]
**Describe the bug**

`brew install mermaid-cli` does not install the latest version. 

See 
https://github.com/Homebrew/homebrew-core/issues/100192
and https://github.com/Homebrew/homebrew-core/pull/83338 

~Need to update the formula to work with Apple silicon, and possibly make the formula mac-only (no linux support)~

https://github.com/Homebrew/homebrew-core/blob/HEAD/Formula/mermaid-cli.rb#L6

**Comment by MindaugasLaganeckas** [comment]
@yogurtearl you are welcome to create a PR. I will gladly review it 😄

**Comment by MindaugasLaganeckas** [comment]
@yogurtearl I am not sure what exactly changes are needed to be applied to mermaid-cli project. One thing I can imagine could be to create a PR against the homebrew every time we make a CLI release, but that is a lot of work so help is needed. Regarding the other part of the comment `and possibly make the formula mac-only (no linux support)` - I have no idea what you mean.

**Comment by yogurtearl** [comment]
>One thing I can imagine could be to create a PR against the homebrew every time we make a CLI release, but that is a lot of work so help is needed. 

could use ` brew bump-formula-pr` from you GH action workflows on every release to automate the process.  
https://docs.brew.sh/How-To-Open-a-Homebrew-Pull-Request

> `and possibly make the formula mac-only (no linux support)` - I have no idea what you mean.

been awhile since I wrote that and not sure what I meant either... 😅

**Comment by MindaugasLaganeckas** [comment]
Unfortunately, I do not have mac, where I could experiment and implement the solution. If you create a PR for it, I will gladly accept it 😄

**Comment by m-cat** [comment]
Bump. 🙂

Right now `brew install mermaid-cli` gives me this warning:

```
Warning: mermaid-cli has been deprecated because it installs a pre-built copy of Chromium!
```

**Comment by aloisklink** [comment]
> Warning: mermaid-cli has been deprecated because it installs a pre-built copy of Chromium!

Unfortunately, `mermaid-cli` requires puppeteer, which requires either Chromium or Firefox. And since both Chromium and Firefox are not yet available as Homebrew Formulae (they're just Casks), the Homebrew team has decided to deprecate `meramid-cli`, see https://github.com/Homebrew/homebrew-core/issues/100192#issuecomment-1114289767:

> Closing based on decision from Homebrew side.
> 
> The way forward for `mermaid-cli` formula would be an external Tap, perhaps maintained by upstream or someone else. If one is created, it can be considered for documentation at https://docs.brew.sh/Interesting-Taps-and-Forks

**I'm going to close this as `won't fix`, since the Homebrew team has said they won't be accepting updates to the `mermaid-cli` formula.**

The homebrew team thinks `mermaid-cli` could be turned into a Tap. https://docs.brew.sh/Acceptable-Casks#rejected-casks also says that it might be accepted as a Cask, despite being a CLI software.

**Comment by chopper7500** [comment]
Just for the heck of it I installed it via homebrew (no issues with install) and ran it against a test file but it failed with the following:

```
Error: Could not find Chrome (ver. 131.0.6778.204). This can occur if either
 1. you did not perform an installation before running the script (e.g. `npx puppeteer browsers install chrome-headless-shell`) or
 2. your cache path is incorrectly configured (which is: /Users/craigh/.cache/puppeteer).
For (2), check out our guide on configuring puppeteer at https://pptr.dev/guides/configuration.
    at ChromeLauncher.resolveExecutablePath (file:///opt/homebrew/Cellar/mermaid-cli/11.12.0/libexec/lib/node_modules/@mermaid-js/mermaid-cli/node_modules/puppeteer-core/lib/esm/puppeteer/node/BrowserLauncher.js:266:27)
    at ChromeLauncher.computeLaunchArguments (file:///opt/homebrew/Cellar/mermaid-cli/11.12.0/libexec/lib/node_modules/@mermaid-js/mermaid-cli/node_modules/puppeteer-core/lib/esm/puppeteer/node/ChromeLauncher.js:85:24)
    at async ChromeLauncher.launch (file:///opt/homebrew/Cellar/mermaid-cli/11.12.0/libexec/lib/node_modules/@mermaid-js/mermaid-cli/node_modules/puppeteer-core/lib/esm/puppeteer/node/BrowserLauncher.js:45:28)
    at async run (file:///opt/homebrew/Cellar/mermaid-cli/11.12.0/libexec/lib/node_modules/@mermaid-js/mermaid-cli/src/index.js:551:17)
    at async cli (file:///opt/homebrew/Cellar/mermaid-cli/11.12.0/libexec/lib/node_modules/@mermaid-js/mermaid-cli/src/index.js:214:3)
```

**Comment by FalseDev** [comment]
For what it's worth, I was able to run it with the following environment variable
```bash
export PUPPETEER_EXECUTABLE_PATH="/Applications/Google Chrome.app/Contents/MacOS/Google Chrome"
```

**Comment by tvanyo** [comment]
I've installed 11.12 with homebrew and am able to run without any additional environment variables or issues.

**Comment by HarmonicDisturbance** [comment]
I ran into the same error and @FalseDev 's workaround helped.  Opened #1122
