### ISSUE TITLE
Abstract or static attributes with the official UML syntax using `name: Type`

### ISSUE THREAD

**Issue by AlexanderGrasberger** [mermaid-js/mermaid-cli#289]
**Is your feature request related to a problem? Please describe.**
I realy like the `classDiagram` Feature. We use it in university for our students to quickly and easily make some UML class diagrams for their projects. The only problem is that we can't use the official UML syntax for attributes like this: `-name: String` in conjunction with the **abstract** `*` and **static** `$` flags. This works for an attribute that is build like this: `-String name` but not for `-name: String`.

**Describe the solution you'd like**
I think a useful tool like this should support the official UML attribute syntax.
A possible syntax could look like this `-name1: String*` or maybe this `-name1*: String`

**Additional context**
Here is an example of the current behavior of mermaid:

```
classDiagram
    class Example {
        -name1: String*
        -name2: String$
        -name1*: String
        -name2$: String
        -String name1*
        -String name2$
    }
```
```mermaid
classDiagram
    class Example {
        -name: String*
        -name: String$
        -name*: String
        -name$: String
        -String name*
        -String name$
    }
```

**Comment by MindaugasLaganeckas** [comment]
Hello @AlexanderGrasberger 
Your feature proposal belongs to the https://github.com/mermaid-js/mermaid
mermaid-cli is only a thin client over the mermaid library.
Please, move your issue to https://github.com/mermaid-js/mermaid/issues
