### ISSUE TITLE
v8.4.8 -> v8.5.1 lower quality

### ISSUE THREAD

**Issue by josephzidell** [mermaid-js/mermaid-cli#3]
Just upgraded to v8.5.1 from v8.4.8 and regenerated an image from an `.mmd` file. It seems the quality went down. 

See the difference here
![image](https://user-images.githubusercontent.com/1812443/82273270-0b55f100-994b-11ea-9524-e40ff803da75.png)

**Comment by MindaugasLaganeckas** [comment]
Mermaid CLI is only a thin client over mermaid library. Consider reporting your issue in the mermaid repository.
