### ISSUE TITLE
Release 9.1.1 on NPM

### ISSUE THREAD

**Issue by multimeric** [mermaid-js/mermaid-cli#302]
The release has been tagged [on GitHub](https://github.com/mermaid-js/mermaid-cli/releases/tag/9.1.1) but it's not yet out [on NPM](https://www.npmjs.com/package/@mermaid-js/mermaid-cli)

**Comment by multimeric** [comment]
Brilliant, thank you.

**Comment by MindaugasLaganeckas** [comment]
Thank you for reporting the error 😄
