### ISSUE TITLE
Stable svg/png generation

### ISSUE THREAD

**Issue by elhedran** [mermaid-js/mermaid-cli#33]
**Is your feature request related to a problem? Please describe.**
I'd like to use mermaid-cli as part of a build process, however even with the same source files, unchanged, the output changes.  This is because the random id's used as part of the svg generation are different with each run of the output.

**Describe the solution you'd like**
I'd like to seed the random number generator for the cli tool based off a checksum/md5 sum of the input file.

**Describe alternatives you've considered**
Another alternative would be just to simply fix the seed to a fixed value, and not inspect the input file.   However using a checksum will better ensure output changes with input.

**Additional context**
N/A

**Comment by elhedran** [comment]
This has implications for generating for checking into github markdown (either wiki or otherwise) as well as better cache-busting strategies when deploying for a static website (e.g. don't bust the cache if you don't need to)

**Comment by elhedran** [comment]
Note, the id is generated here: https://github.com/mermaid-js/mermaid/blob/fec155304101c660eaa693f5a45ec57b44c441ad/src/utils.js#L399

It uses Math.random() which cannot have its seed set or reset externally: https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Math/random

It may be possible to just pull in a seedable random number generator: https://www.npmjs.com/package/seedrandom

But then this becomes a ticket across both mermaid-js and mermaid-js-cli

**Comment by elhedran** [comment]
I had a look at what the change may look like.  However not used to using puppeteer and couldn't quite work out how to import seedrandom correctly such that it could be used in the evaluated script.

https://github.com/elhedran/mermaid-cli/commit/5e7af12f0f2fa3d19ff7ce0c204c5d773433ad74

**Comment by MindaugasLaganeckas** [comment]
@elhedran : mermaid-cli is a very thin client for mermaid library. Without a deep knowledge of mermaid library, I would still suspect, that the wanted change should be supported by the main library (mermaid) and the control of it could be exposed to its clients (for example, mermaid-cli). I have a similar problem with regression testing - I cannot simply compare generated svg files even though the input files are constant. I have been inspired to look at percy.io for a possible solution to the problem. I have started working on the draft PR for it. If you agree to my input, please, close this issue and open one in the mermaid project.

**Comment by elhedran** [comment]
Thanks for the feedback.  I'll close this ticket, and open one on mermaid later
