### ISSUE TITLE
Can we output html instead of svg?

### ISSUE THREAD

**Issue by aadamsx** [mermaid-js/mermaid-cli#333]
can we output html instead of svg?

**Comment by aloisklink** [comment]
`<svg>` is valid HTML5, so you should just be able to inline it any modern-ish browser (it's even supported in [Internet Explorer 9](https://developer.mozilla.org/en-US/docs/Web/SVG/Element/svg)!)

See [SVG In HTML Introduction](https://developer.mozilla.org/en-US/docs/Web/SVG/Tutorial/SVG_In_HTML_Introduction).

Although, if you want HTML as the output, it might be worth using https://github.com/mermaid-js/mermaid directly. `mermaid-cli` renders the graphs on your PC (aka server-side rendering), but you may wish to instead render the mermaid diagrams on the client's browser if you've got HTML (client-side rendering).

**Comment by MindaugasLaganeckas** [comment]
Completely agree with @aloisklink Will close this issue now.

**Comment by EvanCarroll** [comment]
> Although, if you want HTML as the output, it might be worth using https://github.com/mermaid-js/mermaid directly. `mermaid-cli` renders the graphs on your PC (aka server-side rendering), but you may wish to instead render the mermaid diagrams on the client's browser if you've got HTML (client-side rendering).

This is what I want. Do you have any more information. The Mermaid repo only links us here for CLI use cases. I want to provide Markdown with embedded Mermaid graphs, `.md` files and generates static `.html`. What tool does this?

**Comment by aloisklink** [comment]
> I want to provide Markdown with embedded Mermaid graphs, `.md` files and generates static `.html`. What tool does this?

You're looking for a Markdown to HTML converter. There's a bunch of tools for it, it depends on what dialect of Markdown you're using, and how you want to install/run the tools.

If you want to generate a website, most static site generators that accept Markdown either have built-in support for Mermaid, or have a Mermaid plugin (see https://www.markdownguide.org/getting-started#documentation).

For example, [Docusaurus](https://docusaurus.io/docs/markdown-features/diagrams) supports Mermaid diagrams.

If you just want to create individual HTML files, I'd recommend:
  - [Pandoc](https://pandoc.org/index.html) if you want a CLI tool (or you want to convert to PDF/DOCX/LATEX).
  - [remark](https://github.com/remarkjs/remark) if you want a Node.JS tool (although I may be a bit a biased, since I have a plugin for remark that adds Mermaid support called [remark-mermaid-dataurl](https://github.com/aloisklink/remark-mermaid-dataurl))

**Comment by EvanCarroll** [comment]
Yeah, that's what I want. I thought the mermaid-cli would work and be preset up so I don't have to go plugin hunting and configuring it. Would be nice if that was a feature. @aadamsx just for curiosity is this also what you were looking to do?

**Comment by MindaugasLaganeckas** [comment]
mermaid-cli is NOT a swiss knife like solution. Ensuring quality of tools that are swiss knife like are very hard (says my personal experience and common practice in the industry). Therefore our approach to the extent we can is to provide you a tool that is similar to other unix/linux command line tools, e.g. a small building block in your pipeline. Thank you @aloisklink for the links above. I will create a documentation page for this usecase.

**Comment by aloisklink** [comment]
> mermaid-cli is NOT a swiss knife like solution

I agree. To be honest, even the Markdown->Markdown conversions that Mermaid supports is a bit of a hack (and we've constantly been finding edge cases for it).

The big problem with Markdown is that there are so many different competing standards of it, like MultiMarkdown, GitHub Flavored Markdown (GFM), Pandoc, Markdown Extra, etc. And sometimes these standards conflict!

The following ```` ```mermaid ```` syntax isn't even allowed by the [original Markdown spec](https://daringfireball.net/projects/markdown/syntax#precode):

````markdown
```mermaid
blah blah blah
```
````

(even with GitHub Flavored Markdown, GitHub is constantly adding new features, and sometimes they even have different GFM parsing in markdown files and in comments like this PR!)

Plus, plain HTML is usually a bit ugly, so you'd often want a Markdown renderer that adds styling and cool CSS/fonts for you :wink:!

> I will create a documentation page for this usecase.

That makes sense! (it might even be worth having a link to it in the `README.md`)

Thanks for asking this question @EvanCarroll! Even if we won't add it to `mermaid-cli`, you're right that there's probably a bunch of users that would be interested in this! If you do find a tool that you liked, feel free to leave a review for it here to help the next users :smile:
