### ISSUE TITLE
`mmdc` cannot render graphs that include hyperlinks.

### ISSUE THREAD

**Issue by MichaelJFishmanBA** [mermaid-js/mermaid-cli#343]
**Describe the bug**
`mmdc` cannot render graphs that use hyperlinks.

**To Reproduce**
Create a file `link.mmd` with the code

```
graph LR
    A[<a href='https://google.com'>google</a>]
```

run
```sh
mmdc -i link.mmd -o link.svg
```

Open `link.svg` in chrome, and note that it is broken.

**Expected behavior**

The svg looks like the graph below with a clickable link (GitHub renders it correctly):

```mermaid
graph LR
    A[<a href='https://google.com'>google</a>]
```

Or like the [output](https://mermaid.ink/svg/pako:eNo1jrEKwjAURX8lvKVLMXuoBUE3Jzsah0fymgSbpqQvg5T-uxH1Tmc493I3MMkSKHAZFy-uNz2LmtO9Q-EzjcfGMy-rktKl5CY6mBSb_sudxP4BLUTKEYOtI9unrYE9RdKgKlrMTw163qtXFotMFxs4ZVAjTiu1gIXT8JoNKM6F_tI5YD0Uf9b-BplDN7w) of [mermaid.live](https://mermaid.live/edit#pako:eNo1jrEKwjAURX8lvKVLMXuoBUE3Jzsah0fymgSbpqQvg5T-uxH1Tmc493I3MMkSKHAZFy-uNz2LmtO9Q-EzjcfGMy-rktKl5CY6mBSb_sudxP4BLUTKEYOtI9unrYE9RdKgKlrMTw163qtXFotMFxs4ZVAjTiu1gIXT8JoNKM6F_tI5YD0Uf9b-BplDN7w)

**Desktop (please complete the following information):**

- OS: macOS Monterey 12.4
- Browser Chrome
- mmdc version: 8.11.0

**Additional context**
I'm trying to use `mmdc` as part of a python program to generate graphs with links.

**Comment by MindaugasLaganeckas** [comment]
Hey @MichaelJFishmanBA the problem may be a very old mermaid version (8.11.0), that you are using. We have a challenge updating memraid-cli for mac users https://github.com/mermaid-js/mermaid-cli/issues/288 Maybe you can try to use our docker image? With docker, you should get access to the latest mermaid-cli release.

**Comment by MichaelJFishmanBA** [comment]
@MindaugasLaganeckas Using the docker version worked. Thanks!

**Comment by MindaugasLaganeckas** [comment]
Fantastic! 😄 We should look into #288 sometime soon 😄
