### ISSUE TITLE
Output filename doesn't respect -e flag

### ISSUE THREAD

**Issue by BenWeatherall** [mermaid-js/mermaid-cli#394]
**Describe the bug**
When using the `-e` flag to change output format, the default filename remains `input_file + ".svg"`

**To Reproduce**

1.  `mmdc -e pdf -i input.mmd`
2. file produced: `input.mmd.svg
3. file format: pdf

**Expected behavior**
1.  `mmdc -e pdf -i input.mmd`
2. file produced: `input.mmd.pdf`
3. file format: pdf

**Desktop (please complete the following information):**

- OS: Ubunti 22.04
- Browser: N/A
- Version @mermaid-js/mermaid-cli 9.1.7

**Comment by OmiCoding** [comment]
Hey! I would like to give this issue a try if it hasn't been assigned yet.

**Comment by aloisklink** [comment]
> Hey! I would like to give this issue a try if it hasn't been assigned yet.

Go ahead :)

By the way, generally there's no need to ask to be assigned to an issue for simple things, you can just create a PR (or maybe a draft PR if it's a very big change and you're not yet finished with it)

**Comment by OmiCoding** [comment]
Thanks for the heads up! Will do for sure!
