### ISSUE TITLE
where is mmdc ?

### ISSUE THREAD

**Issue by wf5w** [mermaid-js/mermaid-cli#418]
I am running Linux Mint 20.3:

I installed mermaid cli and it seems as though it is successful:
$ yarn add @mermaid-js/mermaid-cli

I wanted to go through the examples, but I cannot find mmdc anywhere.
So where is the executable?

Jerry

**Comment by wf5w** [comment]
sorry, y'all:

used fd and didn't find it UNTIL I did a fd -HI to search hidden files!
duh!

found it in ~/node_modules/.bin/
so I just did a soft link to my bin directory (because I would never remember that)!

**Comment by aloisklink** [comment]
No worries! The JavaScript ecosystem is a bit weird; every package manager installs packages locally, so you often have hundreds of `node_modules` folders that take up a lot of space.

As a side-note, [`yarn bin`](https://classic.yarnpkg.com/en/docs/cli/bin) will output this folder (it's usually `node_modules/.bin`, but it depends on your local computer setup).

Most people just use `yarn mmdc` or `yarn <command>` to run a CLI command installed via yarn, see https://classic.yarnpkg.com/en/docs/cli/#locally-installed-clis

**Comment by aloisklink** [comment]
I'm going to closed this as solved, but you're welcome to help improve the docs if you think of anyway to improve them!
