### ISSUE TITLE
Note size is not scaled to be at least as long as the text length (font dependent)

### ISSUE THREAD

**Issue by craigmac** [mermaid-js/mermaid-cli#419]
**Describe the bug**
Text sometimes overflows the boundaries of the Note box behind it.

**To Reproduce**

```mermaid
sequenceDiagram
  accTitle:  playback
  accDescr: Sequence diagram
participant PE
participant ESX Player
Note over PE, ESX Player: Video/audio config can change during play
opt New video frames will be a different configuration
    PE->>ESX Player: ConfigureVideo()
end
opt New audio frames will be a different configuration
    PE->>ESX Player: ConfigureAudio()
end
Note right of ESX Player: Frames requested & appended in parallel
loop Play
    opt If buffer reaches maximum while playing
        ESX Player->>PE: OnEnoughFrames()
    end
    activate ESX Player
    ESX Player->>ESX Player: Play buffered frames
    ESX Player->>PE: CurrentTimeUpdated.Emit()
    deactivate ESX Player
end
```

**Expected behavior**
A Note should adjust it's width to at least the width of the text give to it

**Screenshots**
<img width="554" alt="Screen Shot 2022-11-04 at 4 05 19 PM" src="https://user-images.githubusercontent.com/7416158/200065015-9ad9ccd0-9a9b-4ffa-be1e-91afa71b1308.png">

**Desktop (please complete the following information):**

`mmdc` ran in Docker image 'pandoc/latex:2.18-ubuntu' with custom entrypoint script that installs `npm install @mermaid/mermaid-cli`

**Comment by craigmac** [comment]
Hmm funny enough it works fine with my embedded example above! Is it because of the font spacing, I'm using Noto mono font installed with `apt-get install -y fonts-noto-core fonts-noto-mono`

**Comment by aloisklink** [comment]
> Is it because of the font spacing?

Potentially! How are you generating your diagrams? Going to `.png`/`.pdf` is the most stable, since that means that the fonts are included in your diagram.

However, if you use `.svg` as an output, the fonts are not included in your output file, so the SVG may look different on each computer.

I'd recommend using the `%%{init: {"fontFamily": "monospace"}}%%` Mermaid directive to set the font (replace `"fontFamily": "monospace"` with the name of your font). See https://mermaid-js.github.io/mermaid/#/Setup?id=fontfamily

**Important**: The font needs to be installed on the computer you're running `mmdc` from (e.g. your Docker image).

Also important, if you're outputting an SVG, the font also needs to be installed on each computer you're going to view the SVG from (it might be possible to get around this by using a custom CSS file that downloads fonts, but I've never tried this before, so I don't know if it will work)

Example:

````md
```mermaid
%%{init: {"fontFamily": "monospace"}}%%
sequenceDiagram
  accTitle:  playback
  accDescr: Sequence diagram
participant PE
participant ESX Player
Note over PE, ESX Player: Video/audio config can change during play
opt New video frames will be a different configuration
    PE->>ESX Player: ConfigureVideo()
end
opt New audio frames will be a different configuration
    PE->>ESX Player: ConfigureAudio()
end
Note right of ESX Player: Frames requested & appended in parallel
loop Play
    opt If buffer reaches maximum while playing
        ESX Player->>PE: OnEnoughFrames()
    end
    activate ESX Player
    ESX Player->>ESX Player: Play buffered frames
    ESX Player->>PE: CurrentTimeUpdated.Emit()
    deactivate ESX Player
end
```
````

```mermaid
%%{init: {"fontFamily": "monospace"}}%%
sequenceDiagram
  accTitle:  playback
  accDescr: Sequence diagram
participant PE
participant ESX Player
Note over PE, ESX Player: Video/audio config can change during play
opt New video frames will be a different configuration
    PE->>ESX Player: ConfigureVideo()
end
opt New audio frames will be a different configuration
    PE->>ESX Player: ConfigureAudio()
end
Note right of ESX Player: Frames requested & appended in parallel
loop Play
    opt If buffer reaches maximum while playing
        ESX Player->>PE: OnEnoughFrames()
    end
    activate ESX Player
    ESX Player->>ESX Player: Play buffered frames
    ESX Player->>PE: CurrentTimeUpdated.Emit()
    deactivate ESX Player
end
```

**Comment by craigmac** [comment]
The pipeline is like this: mmdc ran on markdown files to create temp md files with links to png (I tried svgs as well, but they have the same issue), then I pass these temp md files to pandoc to transform to html+CSS first as an intermediary, which is then exported to PDF using the `--pdf-engine` pandoc flag set to use paged-js (tried several others but this one worked the best). Here are my calls to mmdc and pandoc:

```sh
./node_modules/.bin/mmdc \
	--puppeteerConfigFile /data/puppeteer-config.json \
	--input /data/guide.md \
	--output /data/temp-guide.md \
	--outputFormat png \
	--configFile /data/guide-config.json
./node_modules/.bin/mmdc \
	--puppeteerConfigFile /data/puppeteer-config.json \
	--input /data/guide-release-notes.md \
	--output /data/temp-guide-release-notes.md \
	--outputFormat png \
	--configFile /data/guide-config.json

# We need to turn off sandboxing of chrome again or this won't succeed.
# With `--pdf-engine=pagedjs-cli` we can have pandoc pass along options
# using `--pdf-engine-opt=` to turn off sandboxing

pandoc \
	--standalone \
	--output /data/guide.pdf \
	/data/temp-guide.md \
	/data/guide.yaml \
	--pdf-engine=/data/node_modules/.bin/pagedjs-cli \
	--pdf-engine-opt=--browserArgs \
	--pdf-engine-opt=--no-sandbox \
	--css=/data/guide.css

pandoc \
	--standalone \
	--output /data/guide-release-notes.pdf \
	/data/temp-guide-release-notes.md \
	/data/guide-release-notes.yaml \
	--pdf-engine=/data/node_modules/.bin/pagedjs-cli \
	--pdf-engine-opt=--browserArgs \
	--pdf-engine-opt=--no-sandbox \
	--css=/data/guide.css
```

I'll try the inline approach you mentioned, seems like a good workaround. The PDF did included only the fonts we want, Noto Sans and Noto Mono, and didn't require those on other computers (they are embedded in the PDF) so that's not an issue. I'll give an update if that works any better, thanks!

**Comment by aloisklink** [comment]
It might also be worth having a try in <https://mermaid.live>, e.g. (replacing `"fontFamily" with your font) https://mermaid.live/edit#pako:eNqtk01v2zAMhv8KISDFBmTt3YcCQ-sCO6wNkG7YwRdGom1i-vBkKVkQ5L9PstLFWdDbdLEt6n35kBYPQjpFohKLxYEthwoOjWidDU9oWO8bUUEjjLNuHFBSI47HxaKxI_2KZCU9MnYeTWMhLZTylYOmCmDQuN-g_Pk38Eij9BWsTzpQc-GAPrDkAW2AVX29V69_wCo5ki-xZxcI3JZ8Or2cRSv4zorcHUbFDqSzLXcg0YLs0XYpafRsuwmuGLkhwDPtYJtl0CYgGmHHWsOGABNk25KnRFC8osfAzhZtXqv60_39PP_D6RxNIB8-lqNk1WW-Avg_833Ojlf5pkZ57voArr1o1FPJ7fP_GAMpuAEchiRMr2xz91Fr0sVGOzdMyjNJruRLC5uYiZMNyj7ZGfzNJhrY9axp6nPq91mU1xkilbKqK3ixtXWx6wvRWwkXZZQ7FHiLqZx_L8OV6bzM_DxBpsJKw9-RZZaH6HP7X9nQt0GlbOq2NhzmUIreJZl4xVIY8gZZpZk6lEBjj2k7To614uC8qIKPtBQYg1vvrXz7LmdOUyWqFvWYdmnSfC1zOo3r8Q9btzcO

If it is happening there too, then it's an issue with the upstream https://github.com/mermaid-js/mermaid project.

**Comment by craigmac** [comment]
Sorry, I'm not familiar with the mermaid.live setup, I changed the font but doesn't seem to work for me? Any tips?

**Comment by MindaugasLaganeckas** [comment]
Please, follow the link https://mermaid.live/ and paste your diagram definition into the editor. Afterwards, you can download the diagram in different file formats (png/svg). If you see the same problem as with CLI, then you need to open the bug here https://github.com/mermaid-js/mermaid project.

**Comment by craigmac** [comment]
Thanks @MindaugasLaganeckas ! Yes adding the monospace directive at the top with `%%{init: {"fontFamily": "monospace"}}%%` does trigger overflow of boxes drawn behind (at least for the first label) for some reason the second label auto-adjusts (as it should). Will file upstream.
