### ISSUE TITLE
Take input from STDIN

### ISSUE THREAD

**Issue by alexkrolick** [mermaid-js/mermaid-cli#47]
**Is your feature request related to a problem? Please describe.**

For some diagrams that are generated programatically, it would be great to be able to pipe output from one script straight into mmdc without creating a file.

**Describe the solution you'd like**

Something like this:

```
create-dep-graph.sh | mmdc -o deps.pdf
```

**Describe alternatives you've considered**

🤔 create an intermediate file

```
create-dep-graph.sh > file.mmd & mmdc -i file.mmd -o deps.pdf
```

**Additional context**

🦖

**Comment by MindaugasLaganeckas** [comment]
@alexkrolick Thank you for your feature proposal. I think this one is more in the league of "nice to have". A PR is very much welcome! 🙂

**Comment by MindaugasLaganeckas** [comment]
@capellini : I would very much like to assign you to this issue.

**Comment by capellini** [comment]
@MindaugasLaganeckas Ok - not a problem.  The important thing is the contribution anyway!
