### ISSUE TITLE
End the Debate what does mmd stand for?

### ISSUE THREAD

**Issue by nickm4062** [mermaid-js/mermaid-cli#52]
There is an ongoing debate amongst our team on what mmd stands for:

going contenders:
MerMaid Diagram
Mermaid MarkDown

**Comment by MindaugasLaganeckas** [comment]
@nickm4062 I have forwarded your question to the Mermaid project core group. :smile:

**Comment by knsv** [comment]
It is the top one! A file with the extension mmd contains the code of a **m**er**m**aid **d**iagram. Mermaid Markdown would be markdown containing text in markdown syntax extended with the capability to render mermaid diagrams as per below.

<pre>
## Diagram 1

```mermaid
flowchart TB
A --> B
```
 </pre>

**Comment by MindaugasLaganeckas** [comment]
The debate can be ended now :smile:
