### ISSUE TITLE
convert to xml mxgraphmodel which is supported by draw.io

### ISSUE THREAD

**Issue by BoovendanM** [mermaid-js/mermaid-cli#581]
convert to xml mxgraphmodel which is supported by draw.io.

This feature will be highly helpful to load the mermaid script generated through ai to draw io for further modifications

**Comment by Yokozuna59** [comment]
draw.io already supports mermaid, just insert the the mermaid code. Here's how to insert mermaid code: https://drawio-app.com/blog/create-mermaid-diagrams-in-draw-io/.

**Comment by BoovendanM** [comment]
Looking forward to use the embedded draw.io with mermaid script dynamically remoted to the drawio in program..

To achieve this need to convert the mermaid script to mxgraph xml which drawio understands..

**Comment by aloisklink** [comment]
It's a good idea @BoovendanM, but I think it's out of scope for the `mermaid-cli` project (especially since none of maintainers of `mermaid-cli` have Draw.IO or MXGraph experience).

My feeling is that this would be a separate package, maybe named something like `mermaid-to-mxgraph`?

**Comment by shannon-calrow** [comment]
Draw.io dumping mermaid as a single, un editable svg is not at all the same as generating the XML ?
Interestingly the fork by draw.io adds some of these capabilities
