### ISSUE TITLE
Frontformatter config is not respected

### ISSUE THREAD

**Issue by TeaDrinkingProgrammer** [mermaid-js/mermaid-cli#621]
**Describe the bug**
The CLI does not respect the use of a config file

**To Reproduce**

1. Make a repro.mmd file with the following contents:
```
---
title: Test
config:
  theme: dark
---
mindmap
  root((ML5))
    Hello world

```
3. Execute the following command in the folder: `mmdc -i ./repro.mmd -o output.png`

**Expected behavior**
Resulting image should have the configuration applied, but has a light theme instead of a dark theme.

**Screenshots**
Resulting image:
![output](https://github.com/mermaid-js/mermaid-cli/assets/20358521/593af0f0-0ed2-470d-9553-873393dbd0cc)

**Desktop (please complete the following information):**

- OS: Fedora 39 KDE
- Browser N.A
- Version 10.6.1

Related to #620

**Comment by aloisklink** [comment]
No worries! Dark theme and dark mode do sound very similar! I guess it only didn't occur to me because I normally only use the forest theme :)
