### ISSUE TITLE
SVG is not displayed corectly in Gimp, Pinta, display or Image viewer

### ISSUE THREAD

**Issue by Mo-way** [mermaid-js/mermaid-cli#717]
### Description

I have a file, say `mwe.mmd`:
```
graph TD;
Harry-- friend -->Ron;
Ron-- Girlfriend -->Hermione;
```

Then I use `mmdc -i mwe.mmd -o mwe.svg` to generate svg output. However, I'm unable to properly view the content, as all texts are missing in Gimp, Pintam and Gnome image Viewer. Inkscape doesn't work at all. The texts are in the svg, I assume, because they display correctly in chrome. Pltform is Ubuntu 22.04.

### What I see 
![offline-viewing-mwe 2024-07-23](https://github.com/user-attachments/assets/fb0c6884-0f30-4961-b4c3-773cfa8bca96)

### Output in browser
![mwe](https://github.com/user-attachments/assets/fd003e41-2bce-4583-857f-e97514252c48)

### Tried solutions

- I tried to add a custom css via -C option, but this seems to be unrelated.
- Also skimmed the [config docs](https://mermaid.js.org/config/setup/modules/mermaidAPI.html), but didn't see anything useful.
- The issue I have with browsers is mainly usability, as zooming and moving around are way more natural to me in the native applications.
- Exporting to PDF from browser somehow works, but becomes unhandy for large diagrams

**Comment by mofosyne** [comment]
Maybe mmdc could have a pipe output when `--output - --outputFormat png` and pipe it to something like `display`

**Comment by Mo-way** [comment]
Duplicate of #691
