### ISSUE TITLE
NPM version vs GitHub

### ISSUE THREAD

**Issue by BastianZim** [mermaid-js/mermaid-cli#78]
Hi,

I'm currently trying to create a brew formula as requested in #25 and am not sure which URL to use for downloading?

Brew generally prefers npm but the newest stable version there is, as far as I can see, 8.8.1 with GitHub already having 8.8.3. Should I still use npm?

Thanks!

**Comment by MindaugasLaganeckas** [comment]
@BastianZim : please, use NPM. I can see that we had problems deploying to NPM. I will work on those.

**Comment by BastianZim** [comment]
Thank you, will do!
