### ISSUE TITLE
Pie chart? 

### ISSUE THREAD

**Issue by PsykeDady** [mermaid-js/mermaid-cli#80]
why i can't write pie chart? maybe i miss something? 

if  i write this on my terminal: 
```bash
mmdc -i <(echo 'pie
    title Persone che hanno letto tutto l articolo 
    "Nessuno" : 80.00
    "Nessuno, ma arancio" :  20') -o ciao.png
```

the output is:
```bash
node:internal/process/promises:225
          triggerUncaughtException(err, true /* fromPromise */);
          ^

Error: Evaluation failed: Error: Parse error on line 1:
pie    title Person
^
Expecting 'NEWLINE', 'SPACE', 'GRAPH', got 'ALPHA'
    at Yt.parseError (file:///usr/local/share/.config/yarn/global/node_modules/mermaid.cli/mermaid.min.js:1:486512)
etc..
```

other diagrams like `sequenceDiagram` work well

![image](https://user-images.githubusercontent.com/27916449/100479687-38037600-30ef-11eb-9c1f-63f199de4a5b.png)

**Comment by Yash-Singh1** [comment]
Does:
```md
pie title Persone che hanno letto tutto l articolo
    "Nessuno" : 80.00
    "Nessuno, ma arancio" :  20
```
Work?

**Comment by PsykeDady** [comment]
> Does:
> 
> ```lisp
> pie title Persone che hanno letto tutto l articolo
>     "Nessuno" : 80.00
>     "Nessuno, ma arancio" :  20
> ```
> 
> Work?

Same error :\ 
I tried also with explicit file. 
mmmm, are mermaid-cli from mermaidjs repo related to this? seems there are same bug:
https://github.com/mermaidjs/mermaid.cli/issues/81

**Comment by PsykeDady** [comment]
SORRY I'M REALLY STUPID !!!! 
i installed mermaid.cli and NOT  mermaid-cli 
What a shame T.T sorry 

close bug
