### ISSUE TITLE
Missing type declarations in version 11.4.1

### ISSUE THREAD

**Issue by asterikx** [mermaid-js/mermaid-cli#803]
After upgrading from `@mermaid-js/mermaid-cli:11.4.0` to `@mermaid-js/mermaid-cli:11.4.1`, I get the following TS error on the import statements from `@mermaid-js/mermaid-cli`:

```
Could not find a declaration file for module '@mermaid-js/mermaid-cli'. '/Users/erikmuller/app/node_modules/@mermaid-js/mermaid-cli/src/index.js' implicitly has an 'any' type.
  Try `npm i --save-dev @types/mermaid-js__mermaid-cli` if it exists or add a new declaration (.d.ts) file containing `declare module '@mermaid-js/mermaid-cli';`
```

**Comment by aloisklink** [comment]
Thanks for reporting this issue! It should be fixed in [11.4.2](https://github.com/mermaid-js/mermaid-cli/releases/tag/11.4.2)!

**Comment by MindaugasLaganeckas** [comment]
@aloisklink thank you for reacting so quickly to the issue! Do you have an idea why this error was not caught by our regression/e2e tests? Thank you :)

**Comment by aloisklink** [comment]
>  @aloisklink thank you for reacting so quickly to the issue! Do you have an idea why this error was not caught by our regression/e2e tests? Thank you :)

It only affects the result from `npm pack`/`npm publish`, which our tests can't easily cover.

But maybe we could make a separate test using something like https://www.npmjs.com/package/@arethetypeswrong/cli to sanity check whether everything is working.
