### ISSUE TITLE
Different png output from docker vs local package

### ISSUE THREAD

**Issue by ncarboni** [mermaid-js/mermaid-cli#85]
I am using the latest docker image (minlag/mermaid-cli) for converting mmd to png. I am able to obtain an image, but in respect to my local installation (NPM package) the result is quite poor, using the same exact parameters. The quality is a partial issue, the major problem is the presence of large white bands on the top and bottom of the image.

I am using the latest docker image and node v14.8.0

using 
`docker run -v ${PWD}:/mnt/mmd minlag/mermaid-cli -i /mnt/mmd/Artwork_Name.ttl.mmd -o /mnt/mmd/png/test_docker.png -s 2`
I obtain this image

![test_docker](https://user-images.githubusercontent.com/5669838/101266416-ea21ea00-374e-11eb-8ab0-8acf768650a1.png)

using 
`mmdc -i Artwork_Name.ttl.mmd -o png/test_classic.png -s 2`
I instead obtain this one (preferred)

![test_classic](https://user-images.githubusercontent.com/5669838/101266419-ee4e0780-374e-11eb-9b62-5f25e7b30271.png)

Am I doing something wrong? How can I have the same quality of the export using docker?

**Comment by ncarboni** [comment]
Here the content of the mermaid file if you want to try to replicate the issue
```
graph TD
classDef Literal fill:#f2f2f2,stroke:#000000;
classDef CRM_Entity fill:#FFFFFF,stroke:#000000;
classDef Temporal_Entity fill:#00C9E6, stroke:#000000;
classDef Type fill:#E18312, stroke:#000000;
classDef Time-Span fill:#2C9C91, stroke:#000000;
classDef Appellation fill:#FFEB7F, stroke:#000000;
classDef Place fill:#008836, stroke:#000000;
classDef Persistent_Item fill:#B266B2, stroke:#000000;
classDef Conceptual_Object fill:#FFD700, stroke:#000000;
classDef Physical_Thing fill:#D2B48C, stroke:#000000;
classDef Actor fill:#f58aad, stroke:#000000;
classDef PC_Classes fill:#4ce600, stroke:#000000;
classDef Multi fill:#cccccc,stroke:#000000;

0["crm:E22_Human-Made_Object"]:::Physical_Thing -->|crm:P2_has_type| 1["crm:E55_type"]:::Default
2["crm:E33_E41_Linguistic_Appellation"]:::Default -->|frbroo:R64i_was_name_used_by| 3["frbroo:F52_Name_Use_Activity"]:::Temporal_Entity
6["crm:E42_Identifier"]:::Appellation -->|crm:P37i_was_assigned_by| 7["crm:E15_Identifier_Assignment"]:::Temporal_Entity
6["crm:E42_Identifier"]:::Appellation -->|crm:P2_has_type| 8["crm:E55_Type"]:::Type
2["crm:E33_E41_Linguistic_Appellation"]:::Default -->|crm:p72_has_language| 13["crm:E56_Language"]:::Type
0["crm:E22_Human-Made_Object"]:::Physical_Thing -->|crm:P2_has_type| 9["crm:E55_Type"]:::Type
0["crm:E22_Human-Made_Object"]:::Physical_Thing -->|crm:P1_is_identified_by| 16["crm:E33_E41_Linguistic_Appellation"]:::Default
2["crm:E33_E41_Linguistic_Appellation"]:::Default -->|crm:P190_has_symbolic_content| 19[rdfs:Literal]:::Literal
2["crm:E33_E41_Linguistic_Appellation"]:::Default -->|crm:p2_has_type| 22["crm:E55_Type"]:::Type
7["crm:E15_Identifier_Assignment"]:::Temporal_Entity -->|crm:P16_used_specific_object| 11["crm:E73_Information_Object"]:::Conceptual_Object
0["crm:E22_Human-Made_Object"]:::Physical_Thing -->|crm:P1_is_identified_by| 6["crm:E42_Identifier"]:::Appellation
16["crm:E33_E41_Linguistic_Appellation"]:::Default -->|crm:p2_has_type| 24["crm:E55_Type"]:::Type
7["crm:E15_Identifier_Assignment"]:::Temporal_Entity -->|crm:P14_carried_out_by| 26["crm:E39_Actor"]:::Actor
27["crm:E52_Time-Span"]:::Time-Span -->|crm:P82b_end_of_the_end| 28[xsd:dateTime]:::Literal
4["crm:E13_Attribute_Assignment"]:::Temporal_Entity -->|crm:P140_assigned_attribute_to| 3["frbroo:F52_Name_Use_Activity"]:::Temporal_Entity
3["frbroo:F52_Name_Use_Activity"]:::Temporal_Entity -->|crm:P4_has_time-span| 27["crm:E52_Time-Span"]:::Time-Span
16["crm:E33_E41_Linguistic_Appellation"]:::Default -->|crm:P190_has_symbolic_content| 31[rdfs:Literal]:::Literal
6["crm:E42_Identifier"]:::Appellation -->|crm:P190_has_symbolic_content| 35[rdfs:Literal]:::Literal
0["crm:E22_Human-Made_Object"]:::Physical_Thing -->|crm:P1_is_identified_by| 2["crm:E33_E41_Linguistic_Appellation"]:::Default
2["crm:E33_E41_Linguistic_Appellation"]:::Default -->|crm:P141i_was_assigned_by| 4["crm:E13_Attribute_Assignment"]:::Temporal_Entity
16["crm:E33_E41_Linguistic_Appellation"]:::Default -->|crm:p72_has_language| 20["crm:E56_Language"]:::Type
27["crm:E52_Time-Span"]:::Time-Span -->|crm:P82a_begin_of_the_begin| 39[xsd:dateTime]:::Literal
4["crm:E13_Attribute_Assignment"]:::Temporal_Entity -->|crm:P14_carried_out_by| 40["crm:E39_Actor"]:::Actor
```

**Comment by MindaugasLaganeckas** [comment]
@ncarboni : if I get you correctly, the quality of the images has downgraded from 8.7.0 to 8.8.3.2. Can you also try without docker and compare the two versions? I would like to know if the results using local installations are consistent with the docker ones.

**Comment by ncarboni** [comment]
I made a few test and it appears that the quality remains the same depending on the compactness of the diagram. 
For example, this two images are the output of [this](https://gist.github.com/ncarboni/5c423cba662a36e291981ae670e23d64) mermaid input:

## 8.8.4
![output_8-8-4](https://user-images.githubusercontent.com/5669838/102254565-1258d800-3f09-11eb-8e41-86e687e7ea25.png)
## 8.7.0
![output_8-7-0](https://user-images.githubusercontent.com/5669838/102254568-138a0500-3f09-11eb-9274-f1c5fb1040e1.png)

Version 8.8.4 add a bit more of white band on top and bottom (which is nice). However, if we use a less compact diagram, such as [this one](https://gist.github.com/ncarboni/f4b1f0faf881b4f0d9539682d2674598), the white bands on the top and the bottom of the picture become quite large and prominent and, therefore, the quality of the diagram goes down.

## 8.8.4
![names_output_8-8-4](https://user-images.githubusercontent.com/5669838/102255027-c0fd1880-3f09-11eb-8eb3-b54210629458.png)

This does not happen with version 8.7.0.

All the diagrams are produced using  the NPM package (Mac 11.1. Big Sur)
`mmdc -i names_mmd_criteria.mmd -o names_output_8-8-4.png -s 2`

The results are consistent with the docker ones :-)

**Comment by MindaugasLaganeckas** [comment]
I have just made et another mermaid-cli release - 8.8.4-1. We may have had some inconsitencies between mermaid-cli and mermaid package. For more details see: https://github.com/mermaid-js/mermaid-cli/issues/91

You are welcome to try this new release.

BTW, can you try different output types? For example, svg and pdf? Please, let me know how goes.

**Comment by MindaugasLaganeckas** [comment]
@ncarboni : to wrap up the case, the results produced by docker and local installation are consistent. The difference comes from different CLI versions. Since CLI is only a thin client over mermaid-js, I would suggest to open an issue in the mermaid-js project, if you are not happy with the changes in the diagrams. I will close this ticket now. If you disagree with the resolution, you are welcome to reopen the issue again.
