### ISSUE TITLE
Todaymarker parameter in gantt chart doesn't work

### ISSUE THREAD

**Issue by TheAnsIs42** [mermaid-js/mermaid-cli#91]
**Describe the bug**
The todaymarker parameter can not be turned off.

**To Reproduce**
This is the mermaid code
```
gantt
dateFormat YYYY-MM-DD
title 3rd Year project time mangement
todayMarker off

section Modelling
Matlab plotting :des1, 2020-10-21,10d
Gid plotting : 40d
Gid Issues checking :2020-11-08,2020-12-07
QLC3D pre running :2020-11-12,2020-12-17
QLC3D setting file checking:2020-11-15,2020-12-18
GiD running: 2021-01-11,2021-03-15
QLC3D running with issue checking:2021-01-11,2021-03-25
LCview analizing :2021-01-18,2021-03-30
	   
section  
Spring holiday: crit, 2020-12-21,2021-01-10

section Documentation
Progress Report 1 :2020-10-30,2020-11-04
Progress Report 2 :2020-11-20,2020-11-25
December Interim Report :2020-12-04,2020-12-27
Progress Report 3 :2021-02-12,2021-02-17
Impact Statement :2021-02-14,2021-02-24
Final report:2021-02-28,2021-03-31
```

**Screenshots**
This is the screenshot of pdf file produced.
![image](https://user-images.githubusercontent.com/44214674/103171129-9fdee500-4884-11eb-9d9f-32aedd787bfa.png)

**Desktop (please complete the following information):**

- OS: [windows]
- Browser [chrome]
- Version [8.8.4]

**Comment by MindaugasLaganeckas** [comment]
@TheAnsIs42 : thnk you for reporting this error. Unfortunately, mermaid-cli is thin layer over mermaid library, where the magic happens. I recomment, you report this error in the https://github.com/mermaid-js/mermaid project.
Issues, related to todaymarker can be found here: https://github.com/mermaid-js/mermaid/issues?q=is%3Aissue+todaymarker+is%3Aclosed
Hope that helps!

**Comment by GDFaber** [comment]
Hi, it seems mermaid 8.8.4 does this properly. I just tried the example code in the live-editor for mermaid 8.8.4 and hides the today-marker as expected. Is mermaid-cli updated to use mermaid 8.8.4?

[Example in mermaid live-editor](https://mermaid-js.github.io/mermaid-live-editor/#/edit/eyJjb2RlIjoiZ2FudHRcbmRhdGVGb3JtYXQgWVlZWS1NTS1ERFxudGl0bGUgM3JkIFllYXIgcHJvamVjdCB0aW1lIG1hbmdlbWVudFxudG9kYXlNYXJrZXIgb2ZmXG5cbnNlY3Rpb24gTW9kZWxsaW5nXG5NYXRsYWIgcGxvdHRpbmcgOmRlczEsIDIwMjAtMTAtMjEsMTBkXG5HaWQgcGxvdHRpbmcgOiA0MGRcbkdpZCBJc3N1ZXMgY2hlY2tpbmcgOjIwMjAtMTEtMDgsMjAyMC0xMi0wN1xuUUxDM0QgcHJlIHJ1bm5pbmcgOjIwMjAtMTEtMTIsMjAyMC0xMi0xN1xuUUxDM0Qgc2V0dGluZyBmaWxlIGNoZWNraW5nOjIwMjAtMTEtMTUsMjAyMC0xMi0xOFxuR2lEIHJ1bm5pbmc6IDIwMjEtMDEtMTEsMjAyMS0wMy0xNVxuUUxDM0QgcnVubmluZyB3aXRoIGlzc3VlIGNoZWNraW5nOjIwMjEtMDEtMTEsMjAyMS0wMy0yNVxuTEN2aWV3IGFuYWxpemluZyA6MjAyMS0wMS0xOCwyMDIxLTAzLTMwXG5cdCAgIFxuc2VjdGlvbiAgXG5TcHJpbmcgaG9saWRheTogY3JpdCwgMjAyMC0xMi0yMSwyMDIxLTAxLTEwXG5cbnNlY3Rpb24gRG9jdW1lbnRhdGlvblxuUHJvZ3Jlc3MgUmVwb3J0IDEgOjIwMjAtMTAtMzAsMjAyMC0xMS0wNFxuUHJvZ3Jlc3MgUmVwb3J0IDIgOjIwMjAtMTEtMjAsMjAyMC0xMS0yNVxuRGVjZW1iZXIgSW50ZXJpbSBSZXBvcnQgOjIwMjAtMTItMDQsMjAyMC0xMi0yN1xuUHJvZ3Jlc3MgUmVwb3J0IDMgOjIwMjEtMDItMTIsMjAyMS0wMi0xN1xuSW1wYWN0IFN0YXRlbWVudCA6MjAyMS0wMi0xNCwyMDIxLTAyLTI0XG5GaW5hbCByZXBvcnQ6MjAyMS0wMi0yOCwyMDIxLTAzLTMxIiwibWVybWFpZCI6eyJ0aGVtZSI6ImRlZmF1bHQifSwidXBkYXRlRWRpdG9yIjpmYWxzZX0)

**Comment by TheAnsIs42** [comment]
> Hi, it seems mermaid 8.8.4 does this properly. I just tried the example code in the live-editor for mermaid 8.8.4 and hides the today-marker as expected. Is mermaid-cli updated to use mermaid 8.8.4?
> 
> [Example in mermaid live-editor](https://mermaid-js.github.io/mermaid-live-editor/#/edit/eyJjb2RlIjoiZ2FudHRcbmRhdGVGb3JtYXQgWVlZWS1NTS1ERFxudGl0bGUgM3JkIFllYXIgcHJvamVjdCB0aW1lIG1hbmdlbWVudFxudG9kYXlNYXJrZXIgb2ZmXG5cbnNlY3Rpb24gTW9kZWxsaW5nXG5NYXRsYWIgcGxvdHRpbmcgOmRlczEsIDIwMjAtMTAtMjEsMTBkXG5HaWQgcGxvdHRpbmcgOiA0MGRcbkdpZCBJc3N1ZXMgY2hlY2tpbmcgOjIwMjAtMTEtMDgsMjAyMC0xMi0wN1xuUUxDM0QgcHJlIHJ1bm5pbmcgOjIwMjAtMTEtMTIsMjAyMC0xMi0xN1xuUUxDM0Qgc2V0dGluZyBmaWxlIGNoZWNraW5nOjIwMjAtMTEtMTUsMjAyMC0xMi0xOFxuR2lEIHJ1bm5pbmc6IDIwMjEtMDEtMTEsMjAyMS0wMy0xNVxuUUxDM0QgcnVubmluZyB3aXRoIGlzc3VlIGNoZWNraW5nOjIwMjEtMDEtMTEsMjAyMS0wMy0yNVxuTEN2aWV3IGFuYWxpemluZyA6MjAyMS0wMS0xOCwyMDIxLTAzLTMwXG5cdCAgIFxuc2VjdGlvbiAgXG5TcHJpbmcgaG9saWRheTogY3JpdCwgMjAyMC0xMi0yMSwyMDIxLTAxLTEwXG5cbnNlY3Rpb24gRG9jdW1lbnRhdGlvblxuUHJvZ3Jlc3MgUmVwb3J0IDEgOjIwMjAtMTAtMzAsMjAyMC0xMS0wNFxuUHJvZ3Jlc3MgUmVwb3J0IDIgOjIwMjAtMTEtMjAsMjAyMC0xMS0yNVxuRGVjZW1iZXIgSW50ZXJpbSBSZXBvcnQgOjIwMjAtMTItMDQsMjAyMC0xMi0yN1xuUHJvZ3Jlc3MgUmVwb3J0IDMgOjIwMjEtMDItMTIsMjAyMS0wMi0xN1xuSW1wYWN0IFN0YXRlbWVudCA6MjAyMS0wMi0xNCwyMDIxLTAyLTI0XG5GaW5hbCByZXBvcnQ6MjAyMS0wMi0yOCwyMDIxLTAzLTMxIiwibWVybWFpZCI6eyJ0aGVtZSI6ImRlZmF1bHQifSwidXBkYXRlRWRpdG9yIjpmYWxzZX0)

Yes, the same for me in the live editor. How to check the mermaid version used in mermaid-cli, the `mmdc -V` command gives me 8.8.4, I think that is version of mermaid-cli

**Comment by MindaugasLaganeckas** [comment]
@TheAnsIs42 : have you used mermaid-cli in docker container for you tests? If not, please, do so and report your findings here.

@GDFaber & @TheAnsIs42 : dependebot updates the package versions. Here is the PR #86 in the release https://github.com/mermaid-js/mermaid-cli/releases/tag/8.8.4 for the mermaid 8.8.4.

Today I have made yet another release 8.8.4-1, where I have also updated the version of mermaid in the package.json.

**Comment by TheAnsIs42** [comment]
@MindaugasLaganeckas : Sorry that I didn't use docker before, I downloaded it and tried to run mmdc in docker but I can not run it properly in docker.

**Comment by MindaugasLaganeckas** [comment]
@TheAnsIs42 : it seems that the issue has been solved. Please, verify.
