### ISSUE TITLE
Japanese characters don't render when using the Docker image

### ISSUE THREAD

**Issue by talw** [mermaid-js/mermaid-cli#93]
**Describe the bug**
Japanese characters don't render when using the Docker image.
It does work when using the live editor and when using an mmdc installed using yarn however.

**To Reproduce**
in `/tmp/try.mmdc`:

```
graph LR
    A -->|こんにちは| B
```

```
cat /tmp/try.mmdc | docker run --rm -i -v /tmp:/host minlag/mermaid-cli -o /host/output.pdf
```

**Expected behavior**
こんにちは renders correctly

**Screenshots**
![screenshot](https://user-images.githubusercontent.com/1179015/103733794-e0c9bd00-502d-11eb-865b-5bcceeac0eb4.png)

**Desktop:**

- OS: Linux Debian 9

**Comment by MindaugasLaganeckas** [comment]
@talw : does the CLI tool (not the Docker) work correclty with the Japanese characters?

**Comment by talw** [comment]
> @talw : does the CLI tool (not the Docker) work correclty with the Japanese characters?

Thanks, I added that information to the issue description.
The problem is only reproduced when using the container. It renders fine with a yarn-installed executable

**Comment by MindaugasLaganeckas** [comment]
@talw would you be so kind to test the officially released container and not the release candidate? For example, this one: `docker pull minlag/mermaid-cli:8.8.4-1`

**Comment by talw** [comment]
@MindaugasLaganeckas 

Done

```
rm /tmp/output.pdf
cat /tmp/try.mmdc | docker run --rm -i -v /tmp:/host minlag/mermaid-cli:8.8.4-1 -o /host/output.pdf
```

Same output, unfortunately.

**Comment by MindaugasLaganeckas** [comment]
@talw Thank you so much for trying! 😄

**Comment by MindaugasLaganeckas** [comment]
CC @zionyx

**Comment by MindaugasLaganeckas** [comment]
Fixed by https://github.com/mermaid-js/mermaid-cli/pull/132

**Comment by talw** [comment]
Thanks for the fix!
